In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=sns.load_dataset('iris')

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x=df.drop('species',axis=1)
y=df['species']

In [ ]:
x_train , x_test , y_train ,y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model_knn = KNeighborsClassifier(n_neighbors=5)

In [ ]:
model_knn.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
model_knn.score(x_train,y_train)

0.9666666666666667

In [ ]:
from sklearn.svm import SVC

In [ ]:
model_svm = SVC(gamma='auto') #c=punishment

In [ ]:
model_svm.fit(x_train,y_train)

SVC(gamma='auto')

In [ ]:
model_svm.score(x_train,y_train)

0.9916666666666667

In [ ]:
#now lets use the grid search CV
from sklearn.model_selection import GridSearchCV

In [ ]:
classifier = GridSearchCV((model_svm),{
    'C':[1,20,30],
    'kernel':['linear','rbf']
},cv=5,return_train_score=False)

In [ ]:
#not need to do train test split in cross validation
classifier.fit(x,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 20, 30], 'kernel': ['rbf', 'linear']})

In [ ]:
classifier.fit(x,y)
classifier.cv_results_

{'mean_fit_time': array([0.00189915, 0.00158348, 0.00165873, 0.00223699, 0.00169106,
        0.00162106]),
 'std_fit_time': array([3.44321157e-04, 4.34818494e-05, 1.59003880e-04, 5.16358955e-04,
        4.76072175e-05, 6.35549701e-05]),
 'mean_score_time': array([0.00160398, 0.00122957, 0.00130434, 0.00162306, 0.00127296,
        0.00124745]),
 'std_score_time': array([6.58671904e-04, 5.36481856e-05, 1.51276572e-04, 2.65496729e-04,
        3.43942745e-05, 1.23628473e-04]),
 'param_C': masked_array(data=[1, 1, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'}],
 'split0_test_score': array([0.96666667, 0.96666667, 1.        , 0.96666667, 1.        ,
        0.96666667]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.9       , 0.9       , 0.9       ,
        0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 0.9       ,
        0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.96666667, 0.96666667, 0.96      ,
        0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.0421637 , 0.03651484, 0.04898979,
        0.03887301]),
 'rank_test_score': array([1, 1, 4, 3, 5, 5], dtype=int32)}

In [ ]:
results=pd.DataFrame(classifier.cv_results_)

In [ ]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001899,0.000344,0.001604,0.000659,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.001583,0.000043,0.001230,0.000054,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.001659,0.000159,0.001304,0.000151,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,4
3,0.002237,0.000516,0.001623,0.000265,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,3
4,0.001691,0.000048,0.001273,0.000034,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,5
5,0.001621,0.000064,0.001247,0.000124,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,5

In [ ]:
results[['param_c','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1       linear         0.980000
1        1          rbf         0.980000
2       20       linear         0.966667
3       20          rbf         0.966667
4       30       linear         0.960000
5       30          rbf         0.960000