In [1]:
import pandas as pd
import seaborn as sns

In [3]:
df=sns.load_dataset('taxis')

In [4]:
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [8]:
df.groupby(by='pickup_borough')['fare'].agg(['sum','mean'])

                     sum       mean
pickup_borough
Bronx            2078.91  20.999091
Brooklyn         6327.48  16.520836
Manhattan       58753.42  11.152889
Queens          16382.06  24.934642

In [10]:
df.groupby(by='pickup_borough').agg({'fare':['sum','mean'],'tip':['max','min']})

                    fare               tip
                     sum       mean    max  min
pickup_borough
Bronx            2078.91  20.999091   8.39  0.0
Brooklyn         6327.48  16.520836   7.70  0.0
Manhattan       58753.42  11.152889  20.56  0.0
Queens          16382.06  24.934642  23.19  0.0

In [12]:
df.groupby(by='pickup_borough').agg(total_fare=('fare','sum'),total_tip=('tip','sum'))

                total_fare  total_tip
pickup_borough
Bronx              2078.91      14.71
Brooklyn           6327.48     370.11
Manhattan         58753.42   10217.55
Queens            16382.06    1997.32

In [14]:
df.groupby(by='pickup_borough',as_index=False).agg(total_fare=('fare','sum'),total_tip=('tip','sum'))

  pickup_borough  total_fare  total_tip
0          Bronx     2078.91      14.71
1       Brooklyn     6327.48     370.11
2      Manhattan    58753.42   10217.55
3         Queens    16382.06    1997.32

In [15]:
# dot apply method->custom python function applied on the group
def median_fare(group):
    d_median=group[['tip','fare']].median()
    return d_median

In [18]:
df.groupby(by='pickup_borough').apply(median_fare,include_groups=False)

                 tip  fare
pickup_borough
Bronx           0.00  16.0
Brooklyn        0.00  12.5
Manhattan       1.86   8.5
Queens          0.00  21.0

In [21]:
def range_fare(group):
    range_f=group['fare'].max()-group['fare'].min()
    return range_f

In [22]:
df.groupby(by='pickup_borough').apply(range_fare,include_groups=False)

pickup_borough
Bronx         79.36
Brooklyn      91.00
Manhattan    127.50
Queens       149.00
dtype: float64