In [2]:
import pandas as np
import seaborn as sns

In [8]:
df=sns.load_dataset('taxis') #builtin data set

In [11]:
df['pickup_borough'].unique()

array(['Manhattan', 'Queens', nan, 'Bronx', 'Brooklyn'], dtype=object)

In [12]:
group_pickup=df.groupby(by='pickup_borough')

In [14]:
group_pickup.groups

{'Bronx': [92, 174, 612, 1214, 1848, 1998, 2135, 2391, 2785, 2852, 2908, 4162, 4676, 4696, 4966, 5119, 5457, 5460, 5469, 5471, 5479, 5486, 5504, 5517, 5523, 5549, 5568, 5569, 5591, 5596, 5598, 5600, 5607, 5609, 5616, 5620, 5640, 5650, 5667, 5705, 5720, 5721, 5727, 5735, 5742, 5815, 5817, 5828, 5837, 5840, 5844, 5856, 5863, 5876, 5909, 5910, 5914, 5924, 5936, 5941, 5942, 5947, 5981, 5988, 5991, 6020, 6022, 6048, 6053, 6100, 6103, 6107, 6109, 6120, 6142, 6152, 6174, 6181, 6219, 6221, 6227, 6228, 6256, 6271, 6276, 6279, 6295, 6300, 6318, 6332, 6338, 6346, 6381, 6386, 6387, 6393, 6410, 6413, 6427], 'Brooklyn': [114, 155, 214, 266, 332, 445, 461, 694, 768, 844, 850, 930, 1168, 1218, 1221, 1226, 1288, 1312, 1318, 1341, 1388, 1516, 1666, 1690, 1796, 1820, 1979, 1992, 2164, 2254, 2279, 2327, 2355, 2393, 2452, 2543, 2548, 2669, 2773, 2779, 2817, 2823, 3092, 3129, 3278, 3547, 3555, 3629, 3671, 3679, 3698, 3711, 3776, 3778, 3825, 3835, 3898, 3934, 3963, 4003, 4027, 4476, 4574, 4622, 4640, 4914, 5129, 5190, 5194, 5250, 5455, 5458, 5459, 5461, 5462, 5463, 5464, 5467, 5468, 5473, 5478, 5480, 5484, 5489, 5491, 5497, 5500, 5502, 5503, 5505, 5508, 5511, 5514, 5515, 5516, 5519, 5520, 5521, 5526, 5529, ...], 'Manhattan': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 44, 45, 46, 47, 48, 49, 50, 51, 52, 54, 55, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 89, 90, 91, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 105, 106, 107, 108, ...], 'Queens': [10, 22, 43, 53, 56, 88, 104, 120, 128, 157, 188, 192, 193, 221, 223, 228, 240, 273, 278, 300, 302, 313, 314, 347, 354, 392, 428, 514, 515, 524, 528, 537, 538, 545, 554, 591, 594, 638, 685, 699, 703, 727, 731, 757, 760, 770, 782, 814, 820, 830, 849, 857, 872, 887, 939, 962, 967, 971, 972, 974, 987, 996, 1023, 1041, 1051, 1053, 1059, 1080, 1087, 1089, 1096, 1107, 1118, 1141, 1145, 1147, 1149, 1171, 1176, 1177, 1182, 1186, 1189, 1192, 1215, 1261, 1296, 1305, 1342, 1378, 1384, 1406, 1416, 1450, 1467, 1501, 1503, 1506, 1523, 1530, ...]}

In [15]:
group_pickup.ngroups

4

In [16]:
group_pickup.size()

pickup_borough
Bronx          99
Brooklyn      383
Manhattan    5268
Queens        657
dtype: int64

In [19]:
for name , data in group_pickup:
    print(name)
    print(data)

Bronx
                  pickup             dropoff  passengers  distance   fare  \
92   2019-03-28 07:05:19 2019-03-28 07:41:14           0     10.60  33.50
174  2019-03-04 20:56:26 2019-03-04 21:13:36           1      9.97  28.50
612  2019-03-25 06:31:26 2019-03-25 07:09:53           1     14.74  41.53
1214 2019-03-01 18:02:02 2019-03-01 18:43:57           1      4.89  26.00
1848 2019-03-25 18:15:35 2019-03-25 18:16:08           2      0.07   2.50
...                  ...                 ...         ...       ...    ...
6387 2019-03-29 20:37:59 2019-03-29 20:58:37           1      6.23  18.48
6393 2019-03-10 18:33:13 2019-03-10 19:32:38           1      0.00  71.20
6410 2019-03-08 08:55:42 2019-03-08 09:12:43           1      2.90  13.00
6413 2019-03-22 14:28:22 2019-03-22 14:52:50           1      4.00  13.61
6427 2019-03-23 18:26:09 2019-03-23 18:49:12           1      7.07  20.00

      tip  tolls  total   color      payment  \
92    0.0   5.76  40.06  yellow  credit card
174   0.0   0.00  29.80  yellow  credit card
612   0.0   5.76  48.09  yellow  credit card
1214  0.0   0.00  27.80  yellow  credit card
1848  0.0   0.00   4.30  yellow  credit card
...   ...    ...    ...     ...          ...
6387  0.0   0.00  18.98   green  credit card
6393  0.0   0.00  72.00   green  credit card
6410  0.0   0.00  13.80   green         cash
6413  0.0   0.00  14.11   green  credit card
6427  0.0   0.00  20.00   green         cash

                           pickup_zone                         dropoff_zone  \
92                        East Tremont                         Midtown East
174             Mott Haven/Port Morris  Riverdale/North Riverdale/Fieldston
612              Soundview/Castle Hill             Financial District South
1214  East Concourse/Concourse Village        Westchester Village/Unionport
1848          Williamsbridge/Olinville             Williamsbridge/Olinville
...                                ...                                  ...
6387                       Parkchester                   Woodlawn/Wakefield
6393                       Parkchester                 Flatbush/Ditmas Park
6410                           Belmont           Spuyten Duyvil/Kingsbridge
6413                           Norwood                           Co-Op City
6427                       Parkchester                    East Harlem South

     pickup_borough dropoff_borough
92            Bronx       Manhattan
174           Bronx           Bronx
612           Bronx       Manhattan
1214          Bronx           Bronx
1848          Bronx           Bronx
...             ...             ...
6387          Bronx           Bronx
6393          Bronx        Brooklyn
6410          Bronx           Bronx
6413          Bronx           Bronx
6427          Bronx       Manhattan

[99 rows x 14 columns]
Brooklyn
                  pickup             dropoff  passengers  distance   fare  \
114  2019-03-05 12:17:49 2019-03-05 12:36:12           1      5.98  19.00
155  2019-03-21 22:49:32 2019-03-21 22:55:11           1      1.03   6.00
214  2019-03-22 22:40:19 2019-03-22 22:55:26           1      2.75  12.50
266  2019-03-26 21:42:29 2019-03-26 22:05:23           2      4.40  17.50
332  2019-03-16 01:14:24 2019-03-16 01:26:45           1      2.60  11.00
...                  ...                 ...         ...       ...    ...
6421 2019-03-24 09:07:15 2019-03-24 09:36:45           6     10.23  33.00
6425 2019-03-07 15:34:30 2019-03-07 16:31:06           1      9.12  26.32
6430 2019-03-23 22:55:18 2019-03-23 23:14:25           1      4.14  16.00
6431 2019-03-04 10:09:25 2019-03-04 10:14:29           1      1.12   6.00
6432 2019-03-13 19:31:22 2019-03-13 19:48:02           1      3.85  15.00

       tip  tolls  total   color      payment             pickup_zone  \
114   5.58    0.0  27.88  yellow  credit card        Brooklyn Heights
155   1.46    0.0   8.76  yellow  credit card      DUMBO/Vinegar Hill
214   0.00    0.0  13.80  yellow         cash      Stuyvesant Heights
266   3.76    0.0  22.56  yellow  credit card             Fort Greene
332   0.00    0.0  12.30  yellow         cash     Crown Heights North
...    ...    ...    ...     ...          ...                     ...
6421  0.00    0.0  33.80   green  credit card  East Flatbush/Farragut
6425  0.00    0.0  26.82   green  credit card              Park Slope
6430  0.00    0.0  17.30   green         cash     Crown Heights North
6431  0.00    0.0   6.80   green  credit card           East New York
6432  3.36    0.0  20.16   green  credit card             Boerum Hill

                      dropoff_zone pickup_borough dropoff_borough
114                    Murray Hill       Brooklyn       Manhattan
155               Brooklyn Heights       Brooklyn        Brooklyn
214            Crown Heights North       Brooklyn        Brooklyn
266                  Cypress Hills       Brooklyn        Brooklyn
332            Crown Heights South       Brooklyn        Brooklyn
...                            ...            ...             ...
6421              South Ozone Park       Brooklyn          Queens
6425                 East New York       Brooklyn        Brooklyn
6430                Bushwick North       Brooklyn        Brooklyn
6431  East Flatbush/Remsen Village       Brooklyn        Brooklyn
6432               Windsor Terrace       Brooklyn        Brooklyn

[383 rows x 14 columns]
Manhattan
                  pickup             dropoff  passengers  distance  fare  \
0    2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0
1    2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0
2    2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5
3    2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0
4    2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0
...                  ...                 ...         ...       ...   ...
6420 2019-03-16 15:39:23 2019-03-16 15:46:18           2      1.20   7.0
6422 2019-03-22 20:17:35 2019-03-22 20:36:07           1      4.02  16.0
6424 2019-03-30 20:52:15 2019-03-30 20:59:55           1      1.70   8.0
6426 2019-03-28 08:04:47 2019-03-28 08:07:46           1      0.71   4.5
6428 2019-03-31 09:51:53 2019-03-31 09:55:27           1      0.75   4.5

       tip  tolls  total   color      payment               pickup_zone  \
0     2.15    0.0  12.95  yellow  credit card           Lenox Hill West
1     0.00    0.0   9.30  yellow         cash     Upper West Side South
2     2.36    0.0  14.16  yellow  credit card             Alphabet City
3     6.15    0.0  36.95  yellow  credit card                 Hudson Sq
4     1.10    0.0  13.40  yellow  credit card              Midtown East
...    ...    ...    ...     ...          ...                       ...
6420  0.00    0.0   7.80   green         cash            Central Harlem
6422  0.00    0.0  17.30   green         cash  Washington Heights South
6424  0.00    0.0   9.30   green         cash            Central Harlem
6426  0.50    0.0   5.80   green  credit card              Central Park
6428  1.06    0.0   6.36   green  credit card         East Harlem North

                    dropoff_zone pickup_borough dropoff_borough
0            UN/Turtle Bay South      Manhattan       Manhattan
1          Upper West Side South      Manhattan       Manhattan
2                   West Village      Manhattan       Manhattan
3                 Yorkville West      Manhattan       Manhattan
4                 Yorkville West      Manhattan       Manhattan
...                          ...            ...             ...
6420       Upper West Side North      Manhattan       Manhattan
6422  Spuyten Duyvil/Kingsbridge      Manhattan           Bronx
6424        Central Harlem North      Manhattan       Manhattan
6426       Upper West Side North      Manhattan       Manhattan
6428        Central Harlem North      Manhattan       Manhattan

[5268 rows x 14 columns]
Queens
                  pickup             dropoff  passengers  distance  fare  \
10   2019-03-16 10:02:25 2019-03-16 10:22:29           1      3.90  17.0
22   2019-03-28 17:20:54 2019-03-28 17:55:57           1      9.82  31.5
43   2019-03-27 19:39:16 2019-03-27 20:00:26           1      9.50  28.0
53   2019-03-20 18:49:24 2019-03-20 19:12:40           1     13.45  36.0
56   2019-03-05 17:57:00 2019-03-05 18:45:25           2     19.59  52.0
...                  ...                 ...         ...       ...   ...
6403 2019-03-22 03:28:18 2019-03-22 03:43:44           4      4.07  14.5
6417 2019-03-10 12:10:45 2019-03-10 12:43:05           2     11.17  35.0
6418 2019-03-02 21:47:50 2019-03-02 21:55:34           1      1.48   7.5
6423 2019-03-12 08:10:47 2019-03-12 08:35:35           1      4.30  18.5
6429 2019-03-31 17:38:00 2019-03-31 18:34:23           1     18.74  58.0

       tip  tolls  total   color      payment        pickup_zone  \
10    0.00   0.00  17.80  yellow         cash  LaGuardia Airport
22    8.31   5.76  49.87  yellow  credit card  LaGuardia Airport
43    0.00   5.76  35.06  yellow         cash  LaGuardia Airport
53    0.00   0.00  37.80  yellow         cash        JFK Airport
56    0.00   5.76  65.56  yellow  credit card        JFK Airport
...    ...    ...    ...     ...          ...                ...
6403  0.00   0.00  15.80   green         cash           Elmhurst
6417  0.00   5.76  41.56   green  credit card  Hillcrest/Pomonok
6418  1.76   0.00  10.56   green  credit card       Forest Hills
6423  0.00   0.00  19.30   green  credit card       Saint Albans
6429  0.00   0.00  58.80   green  credit card            Jamaica

                          dropoff_zone pickup_borough dropoff_borough
10                             Astoria         Queens          Queens
22       Sutton Place/Turtle Bay North         Queens       Manhattan
43            Washington Heights South         Queens       Manhattan
53                           Sunnyside         Queens          Queens
56               Upper East Side North         Queens       Manhattan
...                                ...            ...             ...
6403                     College Point         Queens          Queens
6417                          Flatiron         Queens       Manhattan
6418                 Kew Gardens Hills         Queens          Queens
6423                 Hillcrest/Pomonok         Queens          Queens
6429  East Concourse/Concourse Village         Queens           Bronx

[657 rows x 14 columns]

In [20]:
group_pickup.get_group('Queens')

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
10,2019-03-16 10:02:25,2019-03-16 10:22:29,1,3.90,17.0,0.00,0.00,17.80,yellow,cash,LaGuardia Airport,Astoria,Queens,Queens
22,2019-03-28 17:20:54,2019-03-28 17:55:57,1,9.82,31.5,8.31,5.76,49.87,yellow,credit card,LaGuardia Airport,Sutton Place/Turtle Bay North,Queens,Manhattan
43,2019-03-27 19:39:16,2019-03-27 20:00:26,1,9.50,28.0,0.00,5.76,35.06,yellow,cash,LaGuardia Airport,Washington Heights South,Queens,Manhattan
53,2019-03-20 18:49:24,2019-03-20 19:12:40,1,13.45,36.0,0.00,0.00,37.80,yellow,cash,JFK Airport,Sunnyside,Queens,Queens
56,2019-03-05 17:57:00,2019-03-05 18:45:25,2,19.59,52.0,0.00,5.76,65.56,yellow,credit card,JFK Airport,Upper East Side North,Queens,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6403,2019-03-22 03:28:18,2019-03-22 03:43:44,4,4.07,14.5,0.00,0.00,15.80,green,cash,Elmhurst,College Point,Queens,Queens
6417,2019-03-10 12:10:45,2019-03-10 12:43:05,2,11.17,35.0,0.00,5.76,41.56,green,credit card,Hillcrest/Pomonok,Flatiron,Queens,Manhattan
6418,2019-03-02 21:47:50,2019-03-02 21:55:34,1,1.48,7.5,1.76,0.00,10.56,green,credit card,Forest Hills,Kew Gardens Hills,Queens,Queens
6423,2019-03-12 08:10:47,2019-03-12 08:35:35,1,4.30,18.5,0.00,0.00,19.30,green,credit card,Saint Albans,Hillcrest/Pomonok,Queens,Queens
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.00,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx

In [23]:
#aggregate
df.groupby(by='pickup_borough')[['fare']].sum()

                    fare
pickup_borough
Bronx            2078.91
Brooklyn         6327.48
Manhattan       58753.42
Queens          16382.06

In [24]:
df.groupby(by='pickup_borough')[['fare']].mean()

                     fare
pickup_borough
Bronx           20.999091
Brooklyn        16.520836
Manhattan       11.152889
Queens          24.934642

In [25]:
df.groupby(by='pickup_borough')[['fare']].max()

                  fare
pickup_borough
Bronx            81.86
Brooklyn         93.50
Manhattan       130.00
Queens          150.00

In [26]:
df.groupby(by='pickup_borough')[['fare']].min()

                fare
pickup_borough
Bronx            2.5
Brooklyn         2.5
Manhattan        2.5
Queens           1.0

In [27]:
df.groupby(by='pickup_borough')[['fare']].count()

                fare
pickup_borough
Bronx             99
Brooklyn         383
Manhattan       5268
Queens           657

In [28]:
df.groupby(by='pickup_borough')[['fare']].describe()

                  fare
                 count       mean        std  min    25%   50%     75%     max
pickup_borough
Bronx             99.0  20.999091  15.240500  2.5  10.75  16.0  30.500   81.86
Brooklyn         383.0  16.520836  13.670890  2.5   7.50  12.5  19.855   93.50
Manhattan       5268.0  11.152889   8.239970  2.5   6.00   8.5  13.000  130.00
Queens           657.0  24.934642  19.636496  1.0   8.50  21.0  36.000  150.00

In [29]:
df.groupby(by='pickup_borough')[['fare','tip','total']].mean()

                     fare       tip      total
pickup_borough
Bronx           20.999091  0.148586  22.765253
Brooklyn        16.520836  0.966345  19.236240
Manhattan       11.152889  1.939550  16.670507
Queens          24.934642  3.040061  31.660107

In [32]:
#subgroup-using more then one column
df.groupby(by=['pickup_borough','color','payment'])[['fare']].mean()

                                        fare
pickup_borough color  payment
Bronx          green  cash          9.404762
                      credit card  24.218226
               yellow cash          9.625000
                      credit card  28.448333
Brooklyn       green  cash         11.078125
                      credit card  18.319907
               yellow cash         11.195652
                      credit card  21.541778
Manhattan      green  cash          8.386861
                      credit card  12.600645
               yellow cash         10.478175
                      credit card  11.433040
Queens         green  cash         10.913793
                      credit card  16.573901
               yellow cash         28.842975
                      credit card  36.616281